meta:
  engine: 4.1.0
units:
  kx: cx
  ky: cy
  px: kx + 3
  py: ky + 3
points:
  zones:
    tetrafingers:
      anchor:
        shift: [150, -150]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          rows:
            top.skip: true
            bottom.skip: true
            symbols.skip: true
          key.height: 2ky
          key.column_net: P21
        pinky:
          key.stagger: 0
          key.column_net: P20
        ring:
          key.stagger: 9
          key.column_net: P19
        home:
          key.stagger: 8
          key.column_net: P18
        index:
          key.stagger: -9
          key.column_net: P15
        inner:
          rows.symbols.skip: true
          key.stagger: -3
          key.column_net: P14
      rows:
        symbols:
          row_net: P8
        bottom:
          row_net: P9
        home:
          row_net: P10
        top:
          row_net: P16
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: tetrafingers_inner_symbols
        shift: [1.5, -1ky - 2.8 + 12]
      columns:
        near:
          key.splay: -40
          rows.upper:
            shift: [0.75kx,2]
            rotate: -8
            column_net: P7
          rows.lower.column_net: P14
        far:
          rows.upper.skip: true
          rows.lower.column_net: P7
          key:
            spread: 1kx + 4
            splay: -17
            origin: [-11, 0]
      rows:
        lower:
          row_net: P8
        upper:
          row_net: P9
  mirror:
    ref: tetrafingers_inner_top
    distance: -50
outlines:
  holes:
    - what: rectangle
      where: true
      bound: false
      size: [14, 14]
  left_lift:
    - what: rectangle
      where: thumb_near_upper
      size: [20, 20]
  right_lift:
    - what: rectangle
      where: mirror_thumb_near_upper
      size: [20, 20]
  holes_and_lift:
    - name: holes
    - operation: stack
      name: left_lift
    - operation: stack
      name: right_lift
  left_plate_outline:
    - what: polygon
      points:
        - ref: tetrafingers_outer_home
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_pinky_top
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_ring_top
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_home_top
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_index_top
          shift: [-0.5px,1py]
        - ref: tetrafingers_inner_top
          shift: [2.175px + 3,1py + 3]
        - ref: thumb_near_upper
          shift: [0.75px + 3,0.75py] # left connector
        - ref: thumb_far_lower # left bottom connector
          shift: [1px,-0.5py]
        - ref: tetrafingers_index_symbols
          shift: [0px,-2.5py]
        - ref: tetrafingers_index_symbols
          shift: [-0.5px,-0.75py - 20]
        - ref: tetrafingers_pinky_symbols
          shift: [-1.36px,-0.75py]
  right_plate_outline:
    - what: polygon
      points:
        - ref: mirror_tetrafingers_inner_top
          shift: [2.175px,1py + 3]
        - ref: mirror_tetrafingers_home_top
          shift: [-0.5px,0.5py + 1]
        - ref: mirror_tetrafingers_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_tetrafingers_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_tetrafingers_outer_home
          shift: [-0.5px,0.5py]
        - ref: mirror_tetrafingers_pinky_symbols
          shift: [-1.36px,-0.75py]
        - ref: mirror_tetrafingers_index_symbols
          shift: [-0.5px,-0.75py - 20]
        - ref: mirror_tetrafingers_index_symbols
          shift: [0px,-2.5py]
        - ref: mirror_thumb_far_lower # right bottom connector
          shift: [1px,-0.5py]
        - ref: mirror_thumb_near_upper # right connector
          shift: [0.75px,0.75py]
  both_plate_outline:
    - what: polygon
      points:
        - ref: tetrafingers_outer_home
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_pinky_top
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_ring_top
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_home_top
          shift: [-0.5px,0.5py]
        - ref: tetrafingers_index_top
          shift: [-0.5px,1py]
        - ref: tetrafingers_inner_top
          shift: [2.175px + 3,1py + 3]
        - ref: mirror_tetrafingers_inner_top
          shift: [2.175px,1py + 3]
        - ref: mirror_tetrafingers_home_top
          shift: [-0.5px,0.5py + 1]
        - ref: mirror_tetrafingers_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_tetrafingers_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_tetrafingers_outer_home # right hand
          shift: [-0.5px,0.5py]
        - ref: mirror_tetrafingers_pinky_symbols
          shift: [-1.36px,-0.75py]
        - ref: mirror_tetrafingers_index_symbols
          shift: [-0.5px,-0.75py]
        - ref: mirror_thumb_near_lower
          shift: [0.5px,-1py]
        - ref: mirror_thumb_far_lower # right bottom connector
          shift: [1px,-0.5py]
        - ref: mirror_thumb_near_upper # right connector
          shift: [0.75px,0.75py]
        - ref: thumb_far_lower # left bottom connector
          shift: [1px,-0.5py]
        - ref: tetrafingers_index_symbols
          shift: [-0.5px,-0.75py - 8]
        - ref: tetrafingers_pinky_symbols
          shift: [-1.36px,-0.75py]
  plate_and_outline:
    - name: both_plate_outline
    - operation: stack
      name: holes_and_lift
pcbs:
  knoblin_left:
    outlines:
      main:
        outline: left_plate_outline
    footprints:
      choc_hotswap:
        what: choc
        where: /^(?:thumb|tetrafingers)[\w-]*$/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes:
        what: thru-hole-diode
        where: /^(?:thumb|tetrafingers)[\w-]*$/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      nice_nano:
        what: nice_nano
        params:
          orientation: "down"
          type: "nicenano"
        where:
          ref: tetrafingers_inner_top
          shift: [30, -3]
          rotate: -180
      nice_view:
        what: nice_view
        params:
          SDA: P6
          SCL: P5
          CS: P4
        where:
          ref: tetrafingers_inner_top
          shift: [40, -15]
          rotate: 90
      knob:
        what: rotary
        params:
          from: NN_107
          to: GND
          A: NN_101
          B: NN_102
          C: GND
        where:
          ref: tetrafingers_inner_bottom
          shift: [24.8, 7]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: tetrafingers_inner_bottom
          shift: [44.5, 6]
          rotate: 90
      power_switch:
        what: slider
        params:
          from: BAT_POS
          to: RAW
        where:
          ref: tetrafingers_inner_bottom
          shift: [46, -10]
          rotate: -90
      battery_pad_pos:
        what: pad
        params:
          front: false
          text: BAT_POS
          net: BAT_POS
          width: 2
          height: 2
        where:
          ref: tetrafingers_inner_bottom
          shift: [36, -10]
      battery_pad_neg:
        what: pad
        params:
          front: false
          text: BAT_NEG
          net: GND
          width: 2
          height: 2
        where:
          ref: tetrafingers_inner_bottom
          shift: [36, -5]
  knoblin_right:
    outlines:
      main:
        outline: right_plate_outline
    footprints:
      choc_hotswap:
        what: choc
        where: /^(?:mirror_thumb|mirror_tetrafingers)[\w-]*$/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes:
        what: thru-hole-diode
        where: /^(?:mirror_thumb|mirror_tetrafingers)[\w-]*$/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      nice_nano:
        what: nice_nano
        params:
          orientation: "down"
          type: "nicenano"
        where:
          ref: mirror_tetrafingers_inner_top
          shift: [28, -3]
          rotate: 0
      nice_view:
        what: nice_view
        params:
          SDA: P6
          SCL: P5
          CS: P4
        where:
          ref: mirror_tetrafingers_inner_top
          shift: [38, -15]
          rotate: -90
      knob:
        what: rotary
        params:
          from: NN_107
          to: GND
          A: NN_101
          B: NN_102
          C: GND
        where:
          ref: mirror_tetrafingers_inner_bottom
          shift: [24.8 - 2, 7]
          rotate: 90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mirror_tetrafingers_inner_bottom
          shift: [42.5, 6]
          rotate: 90
      power_switch:
        what: slider
        params:
          from: BAT_POS
          to: RAW
        where:
          ref: mirror_tetrafingers_inner_bottom
          shift: [44, -10]
          rotate: -90
      battery_pad_pos:
        what: pad
        params:
          front: false
          text: BAT_POS
          net: BAT_POS
          width: 2
          height: 2
        where:
          ref: mirror_tetrafingers_inner_bottom
          shift: [36, -10]
      battery_pad_neg:
        what: pad
        params:
          front: false
          text: BAT_NEG
          net: GND
          width: 2
          height: 2
        where:
          ref: mirror_tetrafingers_inner_bottom
          shift: [36, -5]
      trackpoint_sensor:
        what: sprintek_sk8707_sensor
        params:
          orientation: "up"
          # Board dimensions
          board_width: 13.2
          board_height: 18.29
          # Pad specifications - matching driver board top pads
          pad_count: 4
          pad_spacing: 2.4
          pad_width: 2.25
          pad_height: 2.25
          pad_offset_from_edge: 0.6
          # Layout
          courtyard_margin: 0.5
          label_offset_y: 2.355
          # Adjustable positioning for all pads
          pad_offset_x: 0
          pad_offset_y: 1
          # Net assignments - 4 numbered pads (connect to driver board top pads)
          PAD1: SENSOR_PAD1
          PAD2: SENSOR_PAD2
          PAD3: SENSOR_PAD3
          PAD4: SENSOR_PAD4
        where:
          ref: mirror_tetrafingers_inner_bottom
          shift: [-2.5, -45.5]
      trackpoint_driver:
        what: sprintek_sk8707_driver
        params:
          orientation: "up"
          # Board dimensions
          board_width: 23
          board_height: 14.5
          # Bottom pad set
          bottom_pad_count: 8
          bottom_pad_spacing: 1.8
          bottom_pad_width: 1.0
          bottom_pad_height: 1.2
          bottom_pad_start_x: -8.42
          bottom_pad_offset_from_edge: 0.6
          # Top pad set
          top_pad_count: 4
          top_pad_spacing: 2.4
          top_pad_width: 2.25
          top_pad_height: 2.25
          top_pad_center_x: 0
          top_pad_offset_from_edge: 0.6
          # Layout
          courtyard_margin: 0.5
          label_offset_y: 2.775
          # Adjustable positioning for top pads
          top_pad_offset_x: 0
          top_pad_offset_y: 0
          # Net assignments - Bottom pad set (8 pads, connect to Nice!Nano)
          GND: GND
          DATA: P0.17
          CLK: P0.20
          RST: P0.22
          VCC: VCC
          LEFT: LEFT_BTN
          MIDDLE: MIDDLE_BTN
          RIGHT: RIGHT_BTN
          # Net assignments - Top pad set (4 pads, connect to sensor board)
          TOP_PAD1: SENSOR_PAD1
          TOP_PAD2: SENSOR_PAD2
          TOP_PAD3: SENSOR_PAD3
          TOP_PAD4: SENSOR_PAD4
        where:
          ref: mirror_tetrafingers_home_symbols
          shift: [0, -25]
          rotate: -90
